version: "3.11"

services:
  web-app:
    build: .
    command: sh -c "python music_catalog/manage.py makemigrations && python music_catalog/manage.py migrate && 
            python music_catalog/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_db